### ISSUE TITLE
How can I include your ffmpeg into a C++ project? 

### ISSUE THREAD

**Issue by sztukai** [nyanmisaka/ffmpeg-rockchip#142]
I've tried many ways to import FFmpeg into my C++ project in order to avoid some unnecessary costs, but I haven't been able to succeed all the time.

**Comment by nyanmisaka** [comment]
This project just adds a few codecs and filters, otherwise it is identical to vanilla FFmpeg.

You can ask concrete questions. But there is no general tutorial on how to use the LibAV interface, nor do I plan to write one. Search engines are your best friend. https://soledadpenades.com/posts/2009/linking-with-ffmpegs-libav/
