### ISSUE TITLE
Compile into static form

### ISSUE THREAD

**Issue by geiliwanghaichao** [nyanmisaka/ffmpeg-rockchip#52]
Hi, 
I want to compile FFmpeg into a static form. However, when compiling the MPP library, I specified -DBUILD_STATIC_LIBS=ON, and for rga, I used --default-library=static. When compiling FFmpeg, I set --disable-shared --enable-static. Despite these settings, the resulting MPP library is a dynamic library, as is the rga library, and FFmpeg still has dynamic dependencies. How can I resolve this issue? 
Thank you.

**Comment by nyanmisaka** [comment]
MPP library doesn’t support static build at the moment. Check this upstream issue for more info. https://github.com/rockchip-linux/mpp/issues/525

**Comment by HeyMeco** [comment]
Opening this again since things got merged @ mpp. I was looking into using ffmpeg-rockchip with tvheadend's docker image. The build commands from the wiki gave me a ffmpeg but when I mount it into the docker image its missing the libraries and can't run. Not sure if I need to build it differently. Any help is appreciated!

**Comment by nyanmisaka** [comment]
@HeyMeco Use this instead. Buildng static portable ffmpeg on linux is non-trivial.

https://github.com/MarcA711/Rockchip-FFmpeg-Builds

**Comment by HeyMeco** [comment]
@nyanmisaka the issue persists with the static portable build. I'll wait and try again when the `libvpx` fixes get merged
